'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "@/Components/PrelineScript";
import { Toaster } from "react-hot-toast";
import { AppProvider } from '@/context/AppContext';
import { CartProvider } from '@/context/CartContext';
import { WishlistProvider } from '@/context/WishlistContext';
import TawkChat from "@/Components/TawkChat";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Mitti Mahal",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <CartProvider>
            <WishlistProvider>
              {children}
              <Toaster position="top-center" />
              <PrelineScript />
              <TawkChat />
            </WishlistProvider>
          </CartProvider>
        </AppProvider>
      </body>
    </html>
  );
}